### ISSUE TITLE
express 4.0 support

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/mozpay-js#2]
https://github.com/mozilla/mozpay-js/blob/master/lib/mozpay.js#L102

will break in express 4.0.

should be `req.body.notice` if the parent app has:

`app.use(bodyParser.json());` before `pay.routes(app);`.

Also, will need: `var bodyParser = require('body-parser');`

**Comment by kumar303** [comment]
For details, see https://github.com/mozilla/mozpay-js/pull/3
